#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 10 09:11:15 2020

@author: ivo
"""

import pandas as pd
import numpy as np
from ninolearn.pathes import rawdir
from os.path import join

version = 'undistorted'

path = r'/home/ivo/fort.149'
headers = ['time', 'x', 'y', 'h', 'T', 'u_A', 'T_0', 'wind', 'tau_x']
data = pd.DataFrame(np.genfromtxt(path), columns=headers)

t_length = int((data['time'].iloc[-1] - data['time'].iloc[0]) /(3600 * 365 *24 ))

data.to_csv(join(rawdir, 'ZCraw_'+f'{t_length}yrs_{version}'))